org.gradle.jvmargs=-Xmx4G

# Minecraft / mappings / loader
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Fabric API
fabric_version=0.138.2+1.21.11

loom_version=1.16-SNAPSHOT

# Mod Menu
modmenu_version=13.0.3

# Mod properties
maven_group=ru.deceased16.ygmemepad
archives_base_name=YGMemePad
mod_version=1.0
